{% set name = "mssql-tools" %}
{% set version = "14.0.5.0" %}
{% set sha256 = "d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/m/mssql-tools/mssql-tools_14.0.5.0-1_amd64.deb

build:
  number: 0
  script:
    - cde $SRC_DIR/
    - dpkg -x $SRC_DIR/mssql-tools/mssql-tools_14.0.5.0-1_amd64.deb extract
    - cp -a extract/opt/mssql-tools/* $PREFIX

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libuuid
    - msodbcsql
  run:
    - libuuid
    - msodbcsql
